import sqlite3
import requests
import json
import logging

logging.basicConfig(level=logging.INFO)

DB_PATH = "backend/dparis.db"
BASE_URL = "https://prayphnadeak-dparis-egsotis.hf.space"
LOGIN_URL = f"{BASE_URL}/api/v1/auth/login"
TRANSPORTATIONS_URL = f"{BASE_URL}/api/v1/transportations/"

# 1. Get auth token
logging.info("Logging in to HF Space API...")
auth_data = {
    "username": "admin",
    "password": "Admin@12345"
}
try:
    auth_resp = requests.post(LOGIN_URL, json=auth_data)
    auth_resp.raise_for_status()
    token = auth_resp.json().get("access_token")
    if not token:
        logging.error("No access token found in login response.")
        exit(1)
    logging.info("Successfully obtained auth token.")
except Exception as e:
    logging.error(f"Login failed: {e}")
    if 'auth_resp' in locals():
        logging.error(f"Response: {auth_resp.text}")
    exit(1)

headers = {
    "Authorization": f"Bearer {token}",
    "Content-Type": "application/json"
}

# 2. Read local transportations
try:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM transportations")
    rows = cursor.fetchall()
    conn.close()
    
    if not rows:
        logging.info("No transportation data found in local DB.")
        exit(0)
    
    logging.info(f"Found {len(rows)} transportations in local DB.")
except Exception as e:
    logging.error(f"Failed to read local DB: {e}")
    exit(1)

# 3. Insert each record to HF Space via API
success_count = 0
for row in rows:
    data = dict(row)
    # Remove metadata fields generated by DB
    data.pop('id', None)
    data.pop('created_at', None)
    data.pop('updated_at', None)
    
    # Convert bools (SQLite uses 0/1)
    bool_fields = [
        'route_palembang', 'route_bengkulu', 'route_lampung', 
        'route_jabodetabek', 'route_jawa', 'is_active'
    ]
    for field in bool_fields:
        if field in data:
            data[field] = bool(data[field])

    # Convert floats or handle nulls
    float_fields = [
        'rating', 'latitude', 'longitude', 'dist_gunung_dempo',
        'dist_pasar_dempo_permai', 'dist_bandara_atung_bungsu',
        'dist_rsud_besemah', 'dist_spbu_air_perikan',
        'dist_spbu_simpang_manna', 'dist_spbu_pengandonan',
        'dist_spbu_karang_dalo'
    ]
    for field in float_fields:
        if field in data and data[field] is not None:
            data[field] = float(data[field])
            
    try:
        resp = requests.post(TRANSPORTATIONS_URL, json=data, headers=headers)
        if resp.status_code == 201:
            success_count += 1
            logging.info(f"Successfully inserted: {data.get('name')}")
        else:
            logging.warning(f"Failed to insert {data.get('name')}. Status: {resp.status_code}, Resp: {resp.text}")
    except Exception as e:
        logging.error(f"Error inserting {data.get('name')}: {e}")

logging.info(f"Successfully synced {success_count} out of {len(rows)} transportations.")
